### ISSUE TITLE
Support collapsing into a single icon 

### ISSUE THREAD

**Issue by ns-jvanderzwaag** [jlorince/GitHubMenuBar#8]
All the icons take up a lot of space in the menu bar and don't display if there is not enough space for all of them. The ability to either dynamically collapse into a single icon or to get that same behavior through an env variable would be useful

**Comment by jlorince** [comment]
This is now supported via the config file, but leaving open until the dynamic toggle works; this will probably happen after a proper config file overhaul (switching to yaml)
